version: '3.4'

services:
  ariana.ecommerce.catalog.api:
    image: ${DOCKER_REGISTRY-}arianaecommercecatalogapi
    build:
      context: .
      dockerfile: Ariana.ECommerce.Catalog.Api/Dockerfile

  sql.data:
    image: mcr.microsoft.com/mssql/server
