version: '3.4'

services:
  ariana.ecommerce.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44338
      - ConnectionString=${ARIANA_ECOMMERCE_CATALOG_DB}
      - EventBusConnection=${ARIANA_ECOMMERCE_EVENT_BUS_CONNECTION}
      - EventBusUserName=${ARIANA_ECOMMERCE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ARIANA_ECOMMERCE_SERVICE_BUS_PASSWORD} 
      - EventBusPort=${ARIANA_ECOMMERCE_SERVICE_BUS_PORT}
    ports:
      - "62698:80"
      - "44338:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    restart: on-failure
    depends_on:
      - catalog.database
      - rabbitmq

  ariana.ecommerce.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44319
      - EventBusConnection=${ARIANA_ECOMMERCE_EVENT_BUS_CONNECTION}
      - EventBusUserName=${ARIANA_ECOMMERCE_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ARIANA_ECOMMERCE_SERVICE_BUS_PASSWORD} 
      - EventBusPort=${ARIANA_ECOMMERCE_SERVICE_BUS_PORT}
    ports:
      - "49196:80"
      - "44319:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    restart: on-failure
    depends_on:
      - rabbitmq

  ariana.ecommerce.ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44303
    ports:
      - "57010:80"
      - "44303:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ariana.ecommerce.payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44312
    ports:
      - "50737:80"
      - "44312:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  catalog.database:
    environment:
      - SA_PASSWORD=Pass@w0rd1
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  rabbitmq:
    ports:
      - "15673:15672"  # Important: In a production environment your should remove the external port
      - "5673:5672"    # Important: In a production environment your should remove the external port