version: '3.4'

services:
  ariana.ecommerce.catalog.api:
    image: ${DOCKER_REGISTRY-}arianaecommercecatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Ariana.ECommerce.Catalog.Api/Dockerfile

  ariana.ecommerce.basket.api:
    image: ${DOCKER_REGISTRY-}arianaecommercebasketapi
    build:
      context: .
      dockerfile: Services/Basket/Ariana.ECommerce.Basket.Api/Dockerfile

  sql.data:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: rabbitmq:management
    hostname: ariana-ecommerce-queue

 

